class BaseImageHandler:

    def change_pixel_color(self, coords): ...

    def restore_original(self):
        self.img_modified = self.img_original.copy()
        self.img_display = self.img_modified.copy()

    def adjust_brightness(self): ...
    def display_histogram(self): ...
    def stretch_histogram(self): ...
    def equalize_histogram(self): ...
    def linear_filters(self): ...
    def median_filter(self): ...